version: '3'

services:
  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    image: nginx
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: on-failure

  mariadb:
    build: ./requirements/mariadb/.
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - inception
    restart: on-failure
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress/.
    image: wordpress
    container_name: wordpress
    ports:
      - "9000:9000"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: on-failure

networks:
    inception:
        driver: bridge

volumes:
  db_data:
      driver_opts:
        type: 'none'
        device: /Users/iel-bakk/Desktop/iel-bakk/MDB
        o: bind
  wordpress:
      driver_opts:
        type: 'none'
        device: /Users/iel-bakk/Desktop/iel-bakk/wordpress
        o: bind