version: '3'

services:
  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/http.d
      - ./requirements/nginx/conf/ssl:/etc/nginx/ssl
    ports:
      - "443:443"
    restart: always

  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    restart: always

  wordpress:
    build: ./requirements/wordpress/.
    container_name: wordpress
    ports:
      - "9000:9000"
    volumes:
      - ./requirements/wp:/var/www/html
    env_file:
      - .env
    restart: on-failure